// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 19.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class Assets {
  static const String package = 'fooriend';

  static const String assets_images_brandlogo_png = 'assets/images/brandlogo.png';
  static const String fooriend$assets_images_brandlogo_png = 'packages/fooriend/assets/images/brandlogo.png';

  static const String assets_images_cat_jpg = 'assets/images/cat.jpg';
  static const String fooriend$assets_images_cat_jpg = 'packages/fooriend/assets/images/cat.jpg';

  static const String assets_images_comment_png = 'assets/images/comment.png';
  static const String fooriend$assets_images_comment_png = 'packages/fooriend/assets/images/comment.png';

  static const String assets_images_food_cafe_png = 'assets/images/food_cafe.png';
  static const String fooriend$assets_images_food_cafe_png = 'packages/fooriend/assets/images/food_cafe.png';

  static const String assets_images_food_cn_png = 'assets/images/food_cn.png';
  static const String fooriend$assets_images_food_cn_png = 'packages/fooriend/assets/images/food_cn.png';

  static const String assets_images_food_ita_png = 'assets/images/food_ita.png';
  static const String fooriend$assets_images_food_ita_png = 'packages/fooriend/assets/images/food_ita.png';

  static const String assets_images_food_jp_png = 'assets/images/food_jp.png';
  static const String fooriend$assets_images_food_jp_png = 'packages/fooriend/assets/images/food_jp.png';

  static const String assets_images_food_ramen_png = 'assets/images/food_ramen.png';
  static const String fooriend$assets_images_food_ramen_png = 'packages/fooriend/assets/images/food_ramen.png';

  static const String assets_images_food_wes_png = 'assets/images/food_wes.png';
  static const String fooriend$assets_images_food_wes_png = 'packages/fooriend/assets/images/food_wes.png';

  static const String assets_images_home_png = 'assets/images/home.png';
  static const String fooriend$assets_images_home_png = 'packages/fooriend/assets/images/home.png';

  static const String assets_images_ranking_1_png = 'assets/images/ranking-1.png';
  static const String fooriend$assets_images_ranking_1_png = 'packages/fooriend/assets/images/ranking-1.png';

  static const String assets_images_ranking_2_png = 'assets/images/ranking-2.png';
  static const String fooriend$assets_images_ranking_2_png = 'packages/fooriend/assets/images/ranking-2.png';

  static const String assets_images_ranking_3_png = 'assets/images/ranking-3.png';
  static const String fooriend$assets_images_ranking_3_png = 'packages/fooriend/assets/images/ranking-3.png';

  static const String assets_images_search_png = 'assets/images/search.png';
  static const String fooriend$assets_images_search_png = 'packages/fooriend/assets/images/search.png';

  static const String assets_images_shop_address_png = 'assets/images/shop_address.png';
  static const String fooriend$assets_images_shop_address_png = 'packages/fooriend/assets/images/shop_address.png';

  static const String assets_images_shop_icon_png = 'assets/images/shop_icon.png';
  static const String fooriend$assets_images_shop_icon_png = 'packages/fooriend/assets/images/shop_icon.png';

  static const String assets_images_shop_time_png = 'assets/images/shop_time.png';
  static const String fooriend$assets_images_shop_time_png = 'packages/fooriend/assets/images/shop_time.png';

  static const String assets_images_user_png = 'assets/images/user.png';
  static const String fooriend$assets_images_user_png = 'packages/fooriend/assets/images/user.png';

  static const String assets_images_user_sample_jpg = 'assets/images/user_sample.jpg';
  static const String fooriend$assets_images_user_sample_jpg = 'packages/fooriend/assets/images/user_sample.jpg';
}
